In [1]:
import pandas as pd

ROOT = '/home/nicolo_b/Desktop/PhD/RELIABLE_NAS/NOTEBOOK/FAULT_INJECTOR/VITTFI'
EXPERIMENTS_LOG = f'{ROOT}/training/results/experiments_log.csv'

df = pd.read_csv(EXPERIMENTS_LOG, index_col='run_id')
df = df.drop(columns=['dataset', 'gamma', 'epochs_completed'])

columns = ['network', 'lr', 'final_train_acc', 'final_test_acc', 'sparsity', 'scheduler']

In [ ]:
last_runs = df.loc[df.network == 'VGG13_BN']
last_runs[columns]

In [7]:
resnet_runs = df.loc[(df.network == 'RESNET56') & (df['optimizer']== 'adam')]
resnet_runs[columns]

,network,lr,final_train_acc,final_test_acc,sparsity,scheduler
run_id,,,,,,
001_ADAM_LR_0001_BS_64_EP_150,RESNET56,0.0010,89.724,63.13,NaN,stepLR
002_ADAM_LR_0005_BS_64_EP_150,RESNET56,0.0050,52.472,48.44,NaN,stepLR
003_ADAM_LR_0007_BS_64_EP_150,RESNET56,0.0070,44.342,38.90,NaN,stepLR
004_ADAM_LR_001_BS_64_EP_150,RESNET56,0.0100,35.076,26.16,NaN,stepLR
005_ADAM_LR_0015_BS_64_EP_150,RESNET56,0.0150,26.572,26.66,NaN,stepLR
006_ADAM_LR_0001_BS_32_EP_150,RESNET56,0.0010,82.794,63.83,0.000000,stepLR
007_ADAM_LR_0003_BS_32_EP_150,RESNET56,0.0030,55.844,51.94,0.218750,stepLR
008_ADAM_LR_0005_BS_32_EP_150,RESNET56,0.0050,43.352,41.78,0.468750,stepLR
009_ADAM_LR_0007_BS_32_EP_150,RESNET56,0.0070,32.258,31.56,0.625000,stepLR
010_ADAM_LR_001_BS_32_EP_150,RESNET56,0.0100,26.326,25.22,0.718750,stepLR
011_ADAM_LR_0015_BS_32_EP_150,RESNET56,0.0150,21.396,20.57,0.734375,stepLR
027_ADAM_LR_0001_BS_128_EP_200,RESNET56,0.0010,84.628,64.00,0.000000,stepLR
028_ADAM_LR_00005_BS_64_EP_200,RESNET56,0.0005,88.074,63.26,0.000000,stepLR
029_ADAM_LR_0001_BS_64_EP_200,RESNET56,0.0010,78.638,64.55,0.000000,stepLR

In [2]:
mobile_runs = df.loc[(df.network == 'MOBILENETV2_X1_4') & (df.optimizer == 'adam')]
mobile_runs

,date,network,optimizer,lr,batch_size,weight_decay,epochs,final_train_acc,final_test_acc,sparsity,scheduler
run_id,,,,,,,,,,,
001_ADAM_LR_0001_BS_64_EP_150,2026-05-14,MOBILENETV2_X1_4,adam,0.001,64,0.0005,150,91.422,67.04,0.385114,stepLR
002_ADAM_LR_0005_BS_64_EP_150,2026-05-14,MOBILENETV2_X1_4,adam,0.005,64,0.0005,150,38.598,40.58,0.895787,stepLR
003_ADAM_LR_001_BS_64_EP_150,2026-05-14,MOBILENETV2_X1_4,adam,0.010,64,0.0005,150,21.534,22.50,0.947684,stepLR
004_ADAM_LR_0001_BS_64_EP_200,2026-05-15,MOBILENETV2_X1_4,adam,0.001,64,0.0005,200,95.810,67.88,0.396205,stepLR
005_ADAM_LR_0005_BS_64_EP_200,2026-05-15,MOBILENETV2_X1_4,adam,0.005,64,0.0005,200,40.442,43.35,0.900112,stepLR
006_ADAM_LR_001_BS_64_EP_200,2026-05-15,MOBILENETV2_X1_4,adam,0.010,64,0.0005,200,23.566,26.97,0.953962,stepLR
007_ADAM_LR_0001_BS_64_EP_150,2026-05-15,MOBILENETV2_X1_4,adam,0.001,64,0.0050,150,53.886,51.82,0.669643,stepLR
008_ADAM_LR_0001_BS_64_EP_150,2026-05-15,MOBILENETV2_X1_4,adam,0.001,64,0.0010,150,83.734,65.56,0.444196,stepLR
009_ADAM_LR_0001_BS_64_EP_150,2026-05-15,MOBILENETV2_X1_4,adam,0.001,64,0.0050,150,45.600,47.44,0.683594,stepLR
010_ADAM_LR_0001_BS_64_EP_150,2026-05-15,MOBILENETV2_X1_4,adam,0.001,64,0.0005,150,83.810,67.44,0.389509,stepLR

In [ ]:
mobile_sgd = df.loc[(df['network'] == 'MOBILENETV2_X1_0') 
& (df['optimizer'] == 'sgd') & (df['batch_size'] == 256) & (df['epochs'] == 200)]


mobile_sgd[columns].sort_values(by='lr')

In [7]:
mobilenet_adam = df.loc[(df['network'] == 'MOBILENETV2_X1_0') 
& (df['optimizer'] == 'adam')]

mobilenet_adam[columns].sort_values('lr')

,network,lr,final_train_acc,final_test_acc,sparsity,scheduler
run_id,,,,,,
022_ADAM_LR_00005_BS_64_EP_200,MOBILENETV2_X1_0,0.0005,98.676,67.92,0.000000,stepLR
027_ADAM_LR_00005_BS_64_EP_200,MOBILENETV2_X1_0,0.0005,95.324,66.94,0.000000,stepLR
030_ADAM_LR_00005_BS_128_EP_200,MOBILENETV2_X1_0,0.0005,97.244,66.96,0.000000,stepLR
023_ADAM_LR_0001_BS_64_EP_200,MOBILENETV2_X1_0,0.0010,90.088,67.01,0.107813,stepLR
024_ADAM_LR_0001_BS_64_EP_200,MOBILENETV2_X1_0,0.0010,81.774,66.78,0.221094,stepLR
025_ADAM_LR_0001_BS_64_EP_200,MOBILENETV2_X1_0,0.0010,82.388,66.89,0.221094,stepLR
026_ADAM_LR_0001_BS_64_EP_200,MOBILENETV2_X1_0,0.0010,76.510,65.36,0.281836,stepLR
028_ADAM_LR_0001_BS_64_EP_200,MOBILENETV2_X1_0,0.0010,75.968,65.14,0.298438,stepLR
029_ADAM_LR_0001_BS_128_EP_200,MOBILENETV2_X1_0,0.0010,91.438,66.83,0.033594,stepLR
031_ADAM_LR_00015_BS_64_EP_200,MOBILENETV2_X1_0,0.0015,71.022,64.35,0.433594,stepLR
032_ADAM_LR_0002_BS_64_EP_200,MOBILENETV2_X1_0,0.0020,62.156,60.77,0.575000,stepLR
033_ADAM_LR_00025_BS_64_EP_200,MOBILENETV2_X1_0,0.0025,55.952,56.78,0.661426,stepLR
034_ADAM_LR_0003_BS_64_EP_200,MOBILENETV2_X1_0,0.0030,49.918,49.96,0.699609,stepLR

In [14]:
mobilenet_best_id = [
    '027_ADAM_LR_00005_BS_64_EP_200',
    '025_ADAM_LR_0001_BS_64_EP_200',
    '031_ADAM_LR_00015_BS_64_EP_200',
    '032_ADAM_LR_0002_BS_64_EP_200'
]

# Filtra: prendi solo le righe con quegli ID E solo quelle colonne
df_mobilenet = df.loc[mobilenet_best_id, columns]
df_mobilenet

,network,lr,final_train_acc,final_test_acc,sparsity,scheduler
run_id,,,,,,
027_ADAM_LR_00005_BS_64_EP_200,MOBILENETV2_X1_0,0.0005,95.324,66.94,0.000000,stepLR
025_ADAM_LR_0001_BS_64_EP_200,MOBILENETV2_X1_0,0.0010,82.388,66.89,0.221094,stepLR
031_ADAM_LR_00015_BS_64_EP_200,MOBILENETV2_X1_0,0.0015,71.022,64.35,0.433594,stepLR
032_ADAM_LR_0002_BS_64_EP_200,MOBILENETV2_X1_0,0.0020,62.156,60.77,0.575000,stepLR

In [2]:
shuffle = df.loc[df['network'] == 'SHUFFLENETV2_X1_0']
shuffle

,date,network,optimizer,lr,batch_size,weight_decay,epochs,final_train_acc,final_test_acc,sparsity,scheduler
run_id,,,,,,,,,,,
001_ADAM_LR_00005_BS_64_EP_200,2026-06-10,SHUFFLENETV2_X1_0,adam,0.0005,64,0.0005,200,96.708,64.40,0.704285,stepLR
003_ADAM_LR_00015_BS_64_EP_200,2026-06-10,SHUFFLENETV2_X1_0,adam,0.0015,64,0.0005,200,79.154,64.32,0.892090,stepLR
004_ADAM_LR_0002_BS_64_EP_200,2026-06-10,SHUFFLENETV2_X1_0,adam,0.0020,64,0.0005,200,71.312,62.45,0.914551,stepLR
005_ADAM_LR_00001_BS_64_EP_200,2026-06-11,SHUFFLENETV2_X1_0,adam,0.0001,64,0.0005,200,99.636,55.20,0.000000,stepLR
006_SGD_LR_01_BS_256_EP_200,2026-06-11,SHUFFLENETV2_X1_0,sgd,0.1000,256,0.0005,200,99.990,72.21,0.000000,cosineAnnealingLR
007_SGD_LR_05_BS_256_EP_200,2026-06-11,SHUFFLENETV2_X1_0,sgd,0.5000,256,0.0005,200,92.904,67.57,0.022461,cosineAnnealingLR