In [1]:
import pandas as pd

ROOT = '/home/nicolo_b/Desktop/PhD/RELIABLE_NAS/NOTEBOOK/FAULT_INJECTOR/VITTFI'
EXPERIMENTS_LOG = f'{ROOT}/training/results/experiments_log.csv'

df = pd.read_csv(EXPERIMENTS_LOG, index_col='run_id')
df = df.drop(columns=['dataset', 'gamma', 'epochs_completed'])

columns = ['network', 'lr', 'final_train_acc', 'final_test_acc', 'sparsity', 'scheduler']

In [2]:
last_runs = df.loc[df.network == 'VGG13_BN']
last_runs[columns]

,network,lr,final_train_acc,final_test_acc,sparsity,scheduler
run_id,,,,,,
001_SGD_LR_01_BS_64_EP_200,VGG13_BN,0.10,98.802,70.19,0.890600,cosineAnnealingLR_warmup
002_SGD_LR_01_BS_256_EP_200,VGG13_BN,0.10,99.820,71.22,0.000000,cosineAnnealingLR
003_SGD_LR_03_BS_256_EP_200,VGG13_BN,0.30,99.152,71.87,0.748047,cosineAnnealingLR
004_SGD_LR_05_BS_256_EP_200,VGG13_BN,0.50,1.000,1.00,0.966797,cosineAnnealingLR
005_SGD_LR_07_BS_256_EP_200,VGG13_BN,0.70,1.000,1.00,0.982422,cosineAnnealingLR
006_SGD_LR_09_BS_256_EP_200,VGG13_BN,0.90,1.000,1.00,1.000000,cosineAnnealingLR
007_SGD_LR_015_BS_256_EP_200,VGG13_BN,0.15,99.760,71.72,0.000000,cosineAnnealingLR
008_SGD_LR_02_BS_256_EP_200,VGG13_BN,0.20,99.644,71.83,0.035156,cosineAnnealingLR
009_SGD_LR_025_BS_256_EP_200,VGG13_BN,0.25,99.458,71.83,0.382812,cosineAnnealingLR
010_SGD_LR_035_BS_256_EP_200,VGG13_BN,0.35,98.804,71.23,0.837891,cosineAnnealingLR
011_SGD_LR_04_BS_256_EP_200,VGG13_BN,0.40,98.054,71.38,0.906250,cosineAnnealingLR
012_SGD_LR_045_BS_256_EP_200,VGG13_BN,0.45,96.758,70.50,0.929688,cosineAnnealingLR

In [ ]:
resnet_runs = df.loc[(df.network == 'RESNET56') & (df['optimizer']== 'adam')]
resnet_runs

In [ ]:
mobile_runs = df.loc[(df.network == 'MOBILENETV2_X1_4') & (df.optimizer == 'adam')]
mobile_runs

In [ ]:
mobile_sgd = df.loc[(df['network'] == 'MOBILENETV2_X1_0') 
& (df['optimizer'] == 'sgd') & (df['batch_size'] == 256) & (df['epochs'] == 200)]


mobile_sgd[columns].sort_values(by='lr')

In [ ]:
mobilenet_adam = df.loc[(df['network'] == 'MOBILENETV2_X1_0') 
& (df['optimizer'] == 'adam')]

mobilenet_adam[columns].sort_values('lr')

In [14]:
mobilenet_best_id = [
    '027_ADAM_LR_00005_BS_64_EP_200',
    '025_ADAM_LR_0001_BS_64_EP_200',
    '031_ADAM_LR_00015_BS_64_EP_200',
    '032_ADAM_LR_0002_BS_64_EP_200'
]

# Filtra: prendi solo le righe con quegli ID E solo quelle colonne
df_mobilenet = df.loc[mobilenet_best_id, columns]
df_mobilenet

,network,lr,final_train_acc,final_test_acc,sparsity,scheduler
run_id,,,,,,
027_ADAM_LR_00005_BS_64_EP_200,MOBILENETV2_X1_0,0.0005,95.324,66.94,0.000000,stepLR
025_ADAM_LR_0001_BS_64_EP_200,MOBILENETV2_X1_0,0.0010,82.388,66.89,0.221094,stepLR
031_ADAM_LR_00015_BS_64_EP_200,MOBILENETV2_X1_0,0.0015,71.022,64.35,0.433594,stepLR
032_ADAM_LR_0002_BS_64_EP_200,MOBILENETV2_X1_0,0.0020,62.156,60.77,0.575000,stepLR

In [2]:
shuffle = df.loc[df['network'] == 'SHUFFLENETV2_X1_0']
shuffle

,date,network,optimizer,lr,batch_size,weight_decay,epochs,final_train_acc,final_test_acc,sparsity,scheduler
run_id,,,,,,,,,,,
001_ADAM_LR_00005_BS_64_EP_200,2026-06-10,SHUFFLENETV2_X1_0,adam,0.0005,64,0.0005,200,96.708,64.40,0.704285,stepLR
003_ADAM_LR_00015_BS_64_EP_200,2026-06-10,SHUFFLENETV2_X1_0,adam,0.0015,64,0.0005,200,79.154,64.32,0.892090,stepLR
004_ADAM_LR_0002_BS_64_EP_200,2026-06-10,SHUFFLENETV2_X1_0,adam,0.0020,64,0.0005,200,71.312,62.45,0.914551,stepLR
005_ADAM_LR_00001_BS_64_EP_200,2026-06-11,SHUFFLENETV2_X1_0,adam,0.0001,64,0.0005,200,99.636,55.20,0.000000,stepLR
006_SGD_LR_01_BS_256_EP_200,2026-06-11,SHUFFLENETV2_X1_0,sgd,0.1000,256,0.0005,200,99.990,72.21,0.000000,cosineAnnealingLR
007_SGD_LR_05_BS_256_EP_200,2026-06-11,SHUFFLENETV2_X1_0,sgd,0.5000,256,0.0005,200,92.904,67.57,0.022461,cosineAnnealingLR
008_SGD_LR_02_BS_256_EP_200,2026-06-11,SHUFFLENETV2_X1_0,sgd,0.2000,256,0.0005,200,99.872,70.89,0.000000,cosineAnnealingLR
009_ADAM_LR_00005_BS_64_EP_200,2026-06-11,SHUFFLENETV2_X1_0,adam,0.0005,64,0.0005,200,99.266,65.80,0.541504,stepLR
010_ADAM_LR_0001_BS_64_EP_200,2026-06-11,SHUFFLENETV2_X1_0,adam,0.0010,64,0.0005,200,96.584,65.14,0.796875,stepLR
011_ADAM_LR_00005_BS_256_EP_200,2026-06-11,SHUFFLENETV2_X1_0,adam,0.0005,256,0.0005,200,96.318,65.14,0.156189,stepLR